#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : cis_sobel.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Jun 04 12:59:47 +0800 2021
# SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: cis_sobel.sh [-help]
# usage: cis_sobel.sh [-lib_map_path]
# usage: cis_sobel.sh [-noclean_files]
# usage: cis_sobel.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'cis_sobel.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm util_vector_logic_v2_0_1 xlconstant_v1_1_6 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 smartconnect_v1_0 fifo_generator_v13_2_4)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "cis_sobel.sh - Script generated by export_simulation (Vivado v2019.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_fifo2mig_axi_0_0/sim/cis_sobel_fifo2mig_axi_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_udp_0_0/sim/cis_sobel_udp_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_img_data_pkt_0_0/sim/cis_sobel_img_data_pkt_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_ov5640_rgb565_top_0_0/sim/cis_sobel_ov5640_rgb565_top_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_wr_ddr_fifo_0_0/sim/cis_sobel_wr_ddr_fifo_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_rd_ddr_fifo_0_0/sim/cis_sobel_rd_ddr_fifo_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_and.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_or.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_clk_ibuf.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_infrastructure.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_tempmon.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_arb_mux.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_arb_row_col.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_arb_select.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_cntrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_common.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_compare.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_mach.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_queue.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_state.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_col_mach.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_mc.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_rank_cntrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_rank_common.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_rank_mach.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_round_robin_arb.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_buf.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_gen.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_fi_xor.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_2_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_2_mem_intfc.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_calib_top.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_init.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_top.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_skip_calib_tap.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_cc.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_edge_store.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_meta.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_pd.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_tap_base.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_top.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_cmd.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_rd_data.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_top.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_wr_data.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/cis_sobel_mig_7series_0_0_mig_sim.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/rtl/cis_sobel_mig_7series_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_clk_wiz_0_0/cis_sobel_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_clk_wiz_0_0/cis_sobel_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_util_ds_buf_0_0/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_util_ds_buf_0_0/sim/cis_sobel_util_ds_buf_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_DVP_Capture_0_1/sim/cis_sobel_DVP_Capture_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_util_vector_logic_0_0/sim/cis_sobel_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_util_vector_logic_1_0/sim/cis_sobel_util_vector_logic_1_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_util_vector_logic_0_1/sim/cis_sobel_util_vector_logic_0_1.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_util_vector_logic_1_1/sim/cis_sobel_util_vector_logic_1_1.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_util_vector_logic_2_0/sim/cis_sobel_util_vector_logic_2_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_util_vector_logic_2_1/sim/cis_sobel_util_vector_logic_2_1.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_util_vector_logic_2_2/sim/cis_sobel_util_vector_logic_2_2.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_wr_fifoddr_clr_0_0/sim/cis_sobel_wr_fifoddr_clr_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_rd_fifoddr_clr_0_0/sim/cis_sobel_rd_fifoddr_clr_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_xlconstant_0_0/sim/cis_sobel_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_xlconstant_0_1/sim/cis_sobel_xlconstant_0_1.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_xlconstant_2_0/sim/cis_sobel_xlconstant_2_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_0/sim/bd_0f99_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_1/sim/bd_0f99_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_2/sim/bd_0f99_arsw_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_3/sim/bd_0f99_rsw_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_4/sim/bd_0f99_awsw_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_5/sim/bd_0f99_wsw_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_6/sim/bd_0f99_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/f85e/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_7/sim/bd_0f99_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_8/sim/bd_0f99_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/7de4/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_9/sim/bd_0f99_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_10/sim/bd_0f99_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_11/sim/bd_0f99_sarn_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_12/sim/bd_0f99_srn_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_13/sim/bd_0f99_sawn_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_14/sim/bd_0f99_swn_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_15/sim/bd_0f99_sbn_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_16/sim/bd_0f99_s01mmu_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_17/sim/bd_0f99_s01tr_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_18/sim/bd_0f99_s01sic_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_19/sim/bd_0f99_s01a2s_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_20/sim/bd_0f99_sarn_1.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_21/sim/bd_0f99_srn_1.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_22/sim/bd_0f99_sawn_1.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_23/sim/bd_0f99_swn_1.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_24/sim/bd_0f99_sbn_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_25/sim/bd_0f99_m00s2a_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_26/sim/bd_0f99_m00arn_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_27/sim/bd_0f99_m00rn_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_28/sim/bd_0f99_m00awn_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_29/sim/bd_0f99_m00wn_0.sv" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_30/sim/bd_0f99_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b387/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_31/sim/bd_0f99_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/sim/bd_0f99.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_axi_smc_0/sim/cis_sobel_axi_smc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_rst_mig_7series_0_100M_0/sim/cis_sobel_rst_mig_7series_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_fifo2mig_axi_0_2/sim/cis_sobel_fifo2mig_axi_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_Trash_Risc_0_0/sources_1/ip/reset_sys/sim/reset_sys.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_adv_timer/adv_timer_apb_if.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_adv_timer/apb_adv_timer.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_gpio/apb_gpio.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c/apb_i2c.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_spi_master/apb_spi_master.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_uart/apb_uart.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_adv_timer/comparator.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_biu.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_clk_ctrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_clkgate.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_core.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_cpu.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_cpu_top.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_dtcm_ctrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_dtcm_ram.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_alu.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_alu_bjp.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_alu_csrctrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_alu_dpath.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_alu_lsuagu.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_alu_muldiv.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_alu_rglr.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_branchslv.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_commit.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_csr.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_decode.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_disp.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_excp.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_longpwbck.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_nice.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_oitf.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_regfile.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_exu_wbck.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_ifu.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_ifu_ifetch.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_ifu_ift2icb.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_ifu_litebpu.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_ifu_minidec.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_irq_sync.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_itcm_ctrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_itcm_ram.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_lsu.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_lsu_ctrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_reset_ctrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/soc/e203_soc_top.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core/e203_srams.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/subsys/e203_subsys_clint.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/subsys/e203_subsys_gfcm.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/subsys/e203_subsys_hclkgen.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/subsys/e203_subsys_hclkgen_rstsync.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/subsys/e203_subsys_main.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/subsys/e203_subsys_mems.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/subsys/e203_subsys_nice_core.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/subsys/e203_subsys_perips.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/subsys/e203_subsys_plic.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/subsys/e203_subsys_pll.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/subsys/e203_subsys_pllclkdiv.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/subsys/e203_subsys_top.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c/i2c_master_bit_ctrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c/i2c_master_byte_ctrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_adv_timer/input_stage.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_uart/io_generic_fifo.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_adv_timer/prescaler.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/general/sirv_1cyc_sram_ctrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_AsyncResetReg.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_AsyncResetRegVec.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_AsyncResetRegVec_1.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_AsyncResetRegVec_129.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_AsyncResetRegVec_36.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_DeglitchShiftRegister.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_LevelGateway.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_ResetCatchAndSync.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_ResetCatchAndSync_2.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_aon.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_aon_lclkgen_regs.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_aon_porrst.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_aon_top.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_aon_wrapper.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_clint.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_clint_top.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/debug/sirv_debug_csr.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/debug/sirv_debug_module.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/debug/sirv_debug_ram.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/debug/sirv_debug_rom.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_expl_axi_slv.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_flash_qspi.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_flash_qspi_top.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/general/sirv_gnrl_bufs.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/general/sirv_gnrl_dffs.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/general/sirv_gnrl_icbs.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/general/sirv_gnrl_ram.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_hclkgen_regs.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/fab/sirv_icb1to16_bus.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/fab/sirv_icb1to2_bus.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/fab/sirv_icb1to8_bus.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/debug/sirv_jtag_dtm.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_jtaggpioport.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/mems/sirv_mrom.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/mems/sirv_mrom_top.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_plic_man.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_plic_top.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_pmu.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_pmu_core.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_qspi_arbiter.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_qspi_fifo.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_qspi_media.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_qspi_physical.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_queue.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_queue_1.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_repeater_6.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_rtc.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/general/sirv_sim_ram.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_spi_flashmap.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/general/sirv_sram_icb_ctrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_tl_repeater_5.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_tlfragmenter_qspi_1.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_tlwidthwidget_qspi.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/sirv_wdog.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_spi_master/spi_master_apb_if.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_spi_master/spi_master_clkgen.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_spi_master/spi_master_controller.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_spi_master/spi_master_fifo.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_spi_master/spi_master_rx.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_spi_master/spi_master_tx.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_adv_timer/timer_cntrl.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_adv_timer/timer_module.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_uart/uart_interrupt.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_uart/uart_rx.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_uart/uart_tx.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_adv_timer/up_down_counter.v" \
    "$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/new/TRASH_RISC.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_Trash_Risc_0_0/sim/cis_sobel_Trash_Risc_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_clkdivider_0_0/sim/cis_sobel_clkdivider_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_wr_ddr_fifo_0_1/sim/cis_sobel_wr_ddr_fifo_0_1.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_rd_ddr_fifo_0_2/sim/cis_sobel_rd_ddr_fifo_0_2.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_util_vector_logic_4_0/sim/cis_sobel_util_vector_logic_4_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_util_vector_logic_5_0/sim/cis_sobel_util_vector_logic_5_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_img_data_pkt_0_1/sim/cis_sobel_img_data_pkt_0_1.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_udp_0_1/sim/cis_sobel_udp_0_1.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_MUX2IN1_0_1/sim/cis_sobel_MUX2IN1_0_1.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_MUX2IN1_0_2/sim/cis_sobel_MUX2IN1_0_2.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_MUX2IN1_4bit_0_0/sim/cis_sobel_MUX2IN1_4bit_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_icb_sobel_0_0/sim/cis_sobel_icb_sobel_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1f5a/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_4 $vhdlan_opts \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/c923" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/perips/apb_i2c" +incdir+"$ref_dir/../../../../riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ipshared/d464/sources_1/imports/e203/core" +incdir+"D:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/cis_sobel/ip/cis_sobel_fifo_generator_0_0/sim/cis_sobel_fifo_generator_0_0.v" \
    "$ref_dir/../../../bd/cis_sobel/sim/cis_sobel.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.cis_sobel xil_defaultlib.glbl -o cis_sobel_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./cis_sobel_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./cis_sobel.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key cis_sobel_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc cis_sobel_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./cis_sobel.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: cis_sobel.sh [-help]\n\
Usage: cis_sobel.sh [-lib_map_path]\n\
Usage: cis_sobel.sh [-reset_run]\n\
Usage: cis_sobel.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
