# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.cache/wt [current_project]
set_property parent.project_path C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-100:part0:1.0 [current_project]
set_property ip_repo_paths d:/ProjectVivado/RISC_BUG/RISC_BUG.srcs [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/imports/fifo2mig_axi/fifo2mig_axi.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/imports/rtl/eth/crc32_d4.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/imports/eth/ip_receive.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/imports/eth/ip_send.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/imports/eth/udp.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/imports/rtl/img_data_pkt.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/imports/imports/new/i2c_dri.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/imports/imports/new/i2c_ov5640_rgb565_cfg.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/imports/imports/Desktop/picture_size.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/imports/imports/new/ov5640_rgb565_top.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/new/wr_ddr_fifo.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/new/rd_ddr_fifo.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/imports/DVP_Capture/DVP_Capture.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/new/wr_fifoddr_clr.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/new/rd_fifoddr_clr.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/src/clkdivider.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/new/MUX2IN1.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/new/MUX2IN1_4bit.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/sobel_final/rgbtogray.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/sobel_final/sobel.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/imports/sobel_final/icb_sobel.v
  C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/hdl/cis_sobel_wrapper.v
}
read_ip -quiet C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/ip/sync_fifo_1024x32b/sync_fifo_1024x32b.xci
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/ip/sync_fifo_1024x32b/sync_fifo_1024x32b.xdc]

read_ip -quiet C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/ip/wr_ddr3_fifo/wr_ddr3_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/ip/wr_ddr3_fifo/wr_ddr3_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/ip/wr_ddr3_fifo/wr_ddr3_fifo_clocks.xdc]

read_ip -quiet C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo_clocks.xdc]

add_files C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/cis_sobel.bd
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/constraints/cis_sobel_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_mig_7series_0_0/cis_sobel_mig_7series_0_0/user_design/constraints/cis_sobel_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_clk_wiz_0_0/cis_sobel_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_clk_wiz_0_0/cis_sobel_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_clk_wiz_0_0/cis_sobel_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_util_ds_buf_0_0/cis_sobel_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_util_ds_buf_0_0/cis_sobel_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_1/bd_0f99_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_1/bd_0f99_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_2/bd_0f99_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_3/bd_0f99_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_4/bd_0f99_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_5/bd_0f99_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_6/bd_0f99_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_10/bd_0f99_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_11/bd_0f99_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_12/bd_0f99_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_13/bd_0f99_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_14/bd_0f99_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_15/bd_0f99_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_19/bd_0f99_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_20/bd_0f99_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_21/bd_0f99_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_22/bd_0f99_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_23/bd_0f99_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_24/bd_0f99_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_25/bd_0f99_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_26/bd_0f99_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_27/bd_0f99_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_28/bd_0f99_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_29/bd_0f99_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/bd_0/ip/ip_30/bd_0f99_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_rst_mig_7series_0_100M_0/cis_sobel_rst_mig_7series_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_rst_mig_7series_0_100M_0/cis_sobel_rst_mig_7series_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_Trash_Risc_0_0/sources_1/ip/reset_sys/reset_sys_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_Trash_Risc_0_0/sources_1/ip/reset_sys/reset_sys.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_fifo_generator_0_0/cis_sobel_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/ip/cis_sobel_fifo_generator_0_0/cis_sobel_fifo_generator_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/sources_1/bd/cis_sobel/cis_sobel_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/constrs_1/imports/new/DDR3.xdc
set_property used_in_implementation false [get_files C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/constrs_1/imports/new/DDR3.xdc]

read_xdc C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/constrs_1/imports/new/camera_ov5640.xdc
set_property used_in_implementation false [get_files C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/constrs_1/imports/new/camera_ov5640.xdc]

read_xdc C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/constrs_1/imports/new/ethernet.xdc
set_property used_in_implementation false [get_files C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/constrs_1/imports/new/ethernet.xdc]

read_xdc C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/constrs_1/imports/new/TrashCtrl.xdc
set_property used_in_implementation false [get_files C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/constrs_1/imports/new/TrashCtrl.xdc]

read_xdc C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/constrs_1/new/debug.xdc
set_property used_in_implementation false [get_files C:/Users/15098/Desktop/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640/riscv_sobel_miiudp_ov5640.srcs/constrs_1/new/debug.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cis_sobel_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cis_sobel_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cis_sobel_wrapper_utilization_synth.rpt -pb cis_sobel_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
